spring.application.name=SpringSecurityStudy
spring.datasource.url=jdbc:mysql://localhost:3306/auth
spring.datasource.username=root
spring.datasource.password=tjdduq79!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=mappers/*.xml


jwt.secret=9caea55b759ff2e709d22756335b7951713b2d3ddfe8d44d0e0150582aa9bee8f79a042e002a5a23609680b49b521aafa7926dfa9c8e7c4676f64de18cc4ff62

